---
include:
    - project: 'gitlab-ci-template/ui-template'
      ref: 1.0.113  # Версия (git-тег) шаблона. ИЗМЕНИТЬ НА АКТУАЛЬНУЮ!
      file:
          - 'template-ui.yml'

variables:
    CROSSBUILDER_TEMPLATES_REF: 1.0.113  # Версия (git-тег) шаблона. ИЗМЕНИТЬ НА АКТУАЛЬНУЮ!
    CROSSBUILDER_TEMPLATES_PROJECT: "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ptsecurity.com/gitlab-ci-template/ui-template.git"

image: docker-ui.ptsecurity.ru:444/node:14.16.0-browsers


Publish package release:
    extends:
        - .release-branch
    stage: publish
    dependencies:
        - Prepare Global
        - Prepare Env
    script:
        - yarn run semantic-release
