name: "Publish To NPM"

on:
    push:
        branches:
            - "([0-9])?(.{+([0-9]),x}).x"
            - "main"
            - "next"
            - "alpha"
            - "beta"

jobs:
    build-and-publish:
        name: Build and Publish
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 16.13.0

            - name: Use node_modules cache
              uses: actions/cache@v2
              id: modules-cache
              with:
                path: '**/node_modules'
                key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
                restore-keys: ${{ runner.os }}-modules-

            - name: Install dependencies
              if: steps.modules-cache.outputs.cache-hit != 'true'
              run: npm ci --ignore-scripts

            - name: Lerna bootstrap
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm run lerna -- bootstrap

            - name: NPM publish
              id: publish
              run: npm run semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

